[build]
  command = "pnpm build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' blob: data:; worker-src 'self' blob:; style-src 'self'; script-src 'self'; connect-src 'self'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
